sudo: required

language: rust

cache:
  - apt
  - cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

branches:
  only:
  - master

matrix:
  fast_finish: false
  include:
  - rust: stable

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install --force --git https://github.com/roblabla/cargo-travis --branch cargo22 || echo "cargo-travis already installed"

script:
  - cargo test

after_success:
  - cargo coveralls --exclude-pattern cli/,res/,snap/,target/,tests/,tools/
