[package]
name = "ethabi"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
build = "build.rs"

[dependencies]
rustc-serialize = "0.3"
serde = "0.7"
serde_json = "0.7"
serde_macros = { version = "0.7.0", optional = true }
clippy = { version = "0.0.63", optional = true}

[build-dependencies]
serde_codegen = { version = "0.7.0", optional = true }
syntex = "0.31.0"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

