[package]
name = "ethabi-cli"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
rustc-hex = "1.0"
rustc-serialize = "0.3"
docopt = "0.6"
ethabi = { version = "1.0", path = ".." }

[[bin]]
name = "ethabi"
path = "src/main.rs"
